role = talker
friendly_name = tonegen_milan_3
# stream_addr = 00:00:00:00:00:00
stream_uid = 3
# dest_addr = 00:00:00:00:00:00
max_interval_frames = 1
sr_class = A

max_transit_usec = 500
max_transmit_deficit_usec = 125

report_seconds = 10
ifname = sendmmsg:enp2s0

map_lib = ./libopenavb_map_aaf_audio.so
map_fn = openavbMapAVTPAudioInitialize
map_nv_item_count = 20
map_nv_tx_rate = 8000
map_nv_packing_factor = 1
map_nv_tx_lead_log_every = 0
map_nv_tx_min_lead_usec = 500

intf_lib = ./libopenavb_intf_tonegen.so
intf_fn = openavbIntfToneGenInitialize
intf_nv_tone_hz = 523
intf_nv_on_off_interval_msec = 1000
intf_nv_audio_rate = 48000
intf_nv_audio_bit_depth = 32
intf_nv_audio_channels = 8
intf_nv_volume = 0
intf_nv_jitter_fifo_enable = 1
intf_nv_jitter_fifo_item_count = 64
intf_nv_jitter_fifo_prefill = 16
intf_nv_jitter_fifo_low_water = 12
intf_nv_jitter_fifo_high_water = 48
intf_nv_jitter_fifo_log_interval_sec = 5

thread_rt_priority = 20

# thread_affinity = 0x00000100

spin_wait = 1

batch_factor = 1

map_nv_selected_clock_follow_updates = 1
